### PR TITLE
Provide an adapted implementation of HttpResponseExpectation

### PR DESCRIPTION
**Pull request by vietj**
Motivation:

HttpResponseExpectation as defined in vertx-core is specific to Vert.x Future API and cannot be reused by RxJava as is.

Changes:

Add an adaptor for HttpResponseExpectation that leverages the lift operator to bridge this feature.

### CODE REVIEW

**Review by tsegismont — COMMENTED** [review]
I haven't read the full PR yet as I noticed the implementation consists in a custom operator.

As far as I know, it is recommended to favor composition (`io.reactivex.Single#compose`) instead of custom operators (`io.reactivex.Single#lift`).

As the Javadoc of `lift` suggests, there are some optimizations that a custom operator must implement itself, that built-in operators implement already.

Besides, if I remember correctly, this is what @jponge recommends for Mutiny extensions as well (start with composition and use custom operators as a last resort).

I would imagine the same feature (HttpResponse expectations) will be implemented with composition in Mutiny, it would be nice to be consistent.

I will send a PR to your branch to show the difference (and how small it is in user experience at the same time).

**Comment by vietj** [comment]
excellent @tsegismont I merged your PR

**Comment by tsegismont** [comment]
@vietj I'll look into the build failure. Also, given transformers are safe to share, I think we can add some constants for expectations (I'll update the branch directly).

Then, before merging, we can wait for @jponge feedback (I believe he will be back next Monday)

**Comment by vietj** [comment]
@tsegismont constants is not possible because of the variance that needs to adapt to the actual single type

**Comment by vietj** [comment]
I'll let this PR in your hands @tsegismont

**Comment by jponge** [comment]
Looking into it shortly

**Comment by tsegismont** [comment]
Thanks @jponge

**Pull request merged**
