### PR TITLE
300 Make the ReadStreamSubscriber serialized

### PR DESCRIPTION
**Pull request by NilsRenaud**
Linked to this issue: https://github.com/vert-x3/vertx-rx/issues/300

Ensure the ReadStream handler is never called concurrently.

### CODE REVIEW

**Comment by NilsRenaud** [comment]
( I originally signed off the commit with the wrong mail... this is fixed, how can I relaunch the legal check ><')

**Review by vietj — COMMENTED** [review]
we should try to make `testReadStreamElementsMustBeSerialized` be the same method in `ReadStreamSubscriberTestBase` like other test methods to maintain a single version of it;

**Comment by vietj** [comment]
cc @jponge

**Comment by jponge** [comment]
I will have a look

**Pull request merged**
