### PR TITLE
Cassandra client examples

### PR DESCRIPTION
**Pull request by Sammers21**
Related to "extra doc for vertx-rx" in https://github.com/vert-x3/vertx-cassandra-client/issues/11

### CODE REVIEW

**Comment by Sammers21** [comment]
@tsegismont, @vietj, can you take a look at the PR?

**Comment by Sammers21** [comment]
@vietj, you mean we should have non Rxified version of the example in the https://github.com/vert-x3/vertx-cassandra-client/ repo? Or we need to have an exact copy of the example?

**Comment by Sammers21** [comment]
@vietj, just created a PR with a placeholder for RX

**Comment by vietj** [comment]
can we have more examples ?

**Comment by Sammers21** [comment]
@vietj, how much examples do you think we need?

**Comment by vietj** [comment]
2 or 3 the most important use cases at least

**Comment by Sammers21** [comment]
Just added 2 more examples with `queryStream` and `fullFetch`

**Pull request merged**
