### PR TITLE
Support for custom marshaller

### LINKED ISSUE #34: Variant of RxHelper.unmarhsaller that can use a custom mapper
We use jackson-dataformat-yaml in order to unmarshall YAML content to a POJO. It would be very nice if the unmarshaller had a variant that allowed for sending in a mapper, and delegate that mapper to the relevant operator. 

I can give a stab at implementing this and sending a PR if that is ok. It should really not be that hard.

### PR DESCRIPTION
**Pull request by bjartek**
Fixes #34

### CODE REVIEW

**Comment by vietj** [comment]
I think the yaml dependency could be omitted as this is only an example, no ?

**Comment by vietj** [comment]
have you signed Eclipse CA ?

**Comment by bjartek** [comment]
I just signed the eclipse CA.

**Comment by vietj** [comment]
this branch has conflicts with master, can you resolve them please ?

**Comment by bjartek** [comment]
I see that there is a new TypedReference that has been introduced into the UnmarshalOperator. Do we want this to support a custom mapper as well? Right now there is not constructor  to create a UnmarshalOperator with a TypedReference and a custom Mapper.

**Comment by vietj** [comment]
@bjartek yes

**Comment by bjartek** [comment]
Ok. I will update this PR later today If i can find time. Cannot prioritize this at work atm so it has to be in the evening (eu)

**Comment by vietj** [comment]
@bjartek ok, no problem with that

**Comment by bjartek** [comment]
Sorry for not finding time to fix this. Do you want me to reopen when I find time?

**Comment by vietj** [comment]
@bjartek sure, I was doing some cleanup

**Pull request closed without merging**
