### PR TITLE
Context scheduler

### PR DESCRIPTION
**Pull request by vietj**
Community patch by @kevlarC + improvements.

@kevlarC would you mind to review the pull request please ?

### CODE REVIEW

**Comment by kevlarC** [comment]
@vietj I do have some suggestions to reduce the blocking of the ContextScheduler class. Might need some performance style tests to see if it actually is worth putting in though.
Should I just create another pull request to show the changes.

**Comment by kevlarC** [comment]
@Vietj Im not sure about the blocking side that you requested changes for though ?

**Comment by vietj** [comment]
@kevlarC don't mind about the blocking side, it was an odd suggestion

**Comment by vietj** [comment]
@kevlarC yes provide another PR

**Comment by vietj** [comment]
@kevlarC what do you mean by X thread ? the test uses new Thread() { ... } it's not a Vert.x thread

**Comment by vietj** [comment]
btw do you know you can comment inline on the commits, it would be easier rather than pointing the line :-) ?

**Comment by kevlarC** [comment]
It took a little bit more review and I like the tests they are a bit simpler. Although a little less 'life like' :wink: .
I've only been doing pull requests for a short time and just shortly after I submitted this did I find out about the inline comments :smile: 

Otherwise it looks good to me

**Pull request merged**
