### PR TITLE
Context scheduler does not offload to the correct thread from external thread.

### PR DESCRIPTION
**Pull request by kevlarC**
If you call an observable that calls back on a different thread the offload via observeOn (Scheduler) does not return on the correct thread.
In our case we were calling couchbase rxApi for inserting ext and it returns on an internal thread. Offloading it makes scense so we do not pollute our vertx thread with couchbase threads. In this case we get the wrong thread back and it causes some erratic bahaviour later on.

 @See SchedulerTest.java:testScheduleObserveOnReturnsOnCorrectThread
 @See ContextScheduler.java

### CODE REVIEW

**Comment by vietj** [comment]
looks good, have you signed the Eclipse CLA ?

**Comment by kevlarC** [comment]
Hi,
Yes, I have signed it :D

Kevin.

**Comment by vietj** [comment]
Hi,

I think this is a good patch, however I believe that the same should apply in blocking mode with executeBlocking. Would you mind to do the same and add a test so this fix both cases ?

**Comment by kevlarC** [comment]
Im not sure how to write the test but ill have a lil look in for an hour or
so.

**Comment by kevlarC** [comment]
Ive written this test and it does not fail so Im not sure it needs to be
altered.


@Test
public void testScheduleObserveOnReturnsOnTheCorrectThreadForBlockingVerticle()
{

    AtomicReference<String> vertxThread = new AtomicReference<>();
    AtomicReference<String> scheduleThread = new AtomicReference<>();
    ExecutorService executor = Executors.newSingleThreadExecutor();

    vertx.deployVerticle(new io.vertx.rxjava.core.AbstractVerticle() {
        @Override
        public void start(Future<Void> startFuture) throws Exception {
            Scheduler scheduler = new ContextScheduler(this.getVertx(), false);
            vertxThread.set(Thread.currentThread()
                                  .getName());
            OffLoader offLoader = new OffLoader(executor, vertxThread.get());
            vertx.executeBlockingObservable(offLoader)
                 .observeOn(scheduler)
                 .doOnNext(o -> scheduleThread.set(Thread.currentThread()
                                                         .getName()))
                 .subscribe(o -> startFuture.complete(), o ->
startFuture.fail(o));
        }
    }, future -> {
        if (future.succeeded()) {
            assertEquals("Expected the thread callback on the correct
Vertx Thread.", vertxThread.get(), scheduleThread.get());
            vertx.undeploy(future.result(), o -> {
                executor.shutdown();
                testComplete();
            });
        } else {
            fail("Oops");
            testComplete();
        }
    });
    await();
}

private class OffLoader implements
Handler<io.vertx.rxjava.core.Future<String>> {
    private final Executor executor;
    private final String threadName;

    private OffLoader(Executor executor, String threadName) {
        this.executor = executor;
        this.threadName = threadName;
    }

    public Observable<String> observe() {
        return Observable.create(new Observable.OnSubscribe<String>() {
            @Override
            public void call(Subscriber<? super String> subscriber) {
                executor.execute(() -> {
                    subscriber.onNext(threadName);
                    subscriber.onCompleted();
                });
            }
        });
    }

    @Override
    public void handle(io.vertx.rxjava.core.Future<String> event) {
        executor.execute(() -> {
            event.complete(threadName);
        });
    }
}

**Comment by vietj** [comment]
@kevlarC I've created a branch with your patch + did the implementation for timer. Would you mind to review the PR please ?

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-rx/pull/28

**Comment by vietj** [comment]
Hi,

I'm planning a potential change concerning context : would you mind to look at this branch https://github.com/vert-x3/vertx-rx/tree/capture-context-when-timer-is-created and tell me what you think ?

the related discussion and motivation : https://github.com/vert-x3/vertx-rx/issues/36

**Pull request merged**
