### PR TITLE
Unmarshal Jackson TypeRefernce

### PR DESCRIPTION
**Pull request by bmsantos**
Issue #81

### CODE REVIEW

**Comment by vietj** [comment]
@bmsantos have you signed the Eclipse CA ?

**Comment by bmsantos** [comment]
@vietj, yes I have.

**Comment by vietj** [comment]
have you signed the Eclipse CA bmsantos ?

**Comment by bmsantos** [comment]
@vietj, I did. https://accounts.eclipse.org/users/bsantos1wc
Do you need my email to verify it?

**Comment by vietj** [comment]
that's fine

**Comment by vietj** [comment]
thanks for the contribution!

**Pull request merged**
