### PR TITLE
Use lambda instead of anonymous class

### PR DESCRIPTION
**Pull request by okou19900722**

### CODE REVIEW

**Comment by vietj** [comment]
I believe originally we did not use a lambda because of compiler inference issue (javac), I'm ok using a lambda however I would like to have the type to be specified in the lambda to avoid such issue

**Comment by okou19900722** [comment]
```java
public io.vertx.rxjava.core.file.FileSystem readFile(String path, Handler<AsyncResult<io.vertx.rxjava.core.buffer.Buffer>> handler) {
    delegate.readFile(path, (AsyncResult<io.vertx.core.buffer.Buffer> ar) -> {
      handler.handle(ar.map(r -> io.vertx.rxjava.core.buffer.Buffer.newInstance(r)));
    });
    return this;
  }
```
do you means that?

**Comment by vietj** [comment]
yes

**Comment by okou19900722** [comment]
@vietj it's done, can you review? thanks!

**Comment by tsegismont** [comment]
Sorry for the very late reply @okou19900722 

Closing this one, superseded by https://github.com/vert-x3/vertx-rx/pull/283

**Pull request closed without merging**
