### PR TITLE
Back pressure support for ReadStream / Observable

### PR DESCRIPTION
**Pull request by vietj**
@purplefox  please review this work

### CODE REVIEW

**Comment by purplefox** [comment]
Much of this looks similar to the work that was done already in vertx-reactivestreams.

Wouldn't it be possible to just use that along with https://github.com/ReactiveX/RxJavaReactiveStreams in order to implement the back pressure?

**Comment by vietj** [comment]
I will give a try to see how it goes, can you still have a look at the impl and see if that's the correct way to do ?

**Comment by purplefox** [comment]
Sure :)

**Comment by vietj** [comment]
I have investigated a bit, that's doable technically, here is my summary

- it reuses existing code that's something good
- it makes things more complex : a mix of vertx-reactive-streams / rxjava-reactive-streams / rxjava
- the code needs to access a vertx instance for calling getOrCreateContext() and that object is not accessible when we need it (in the RxJava generated api) so there should be a workaround / solution for that

**Comment by vietj** [comment]
invalid as implemented by another PR

**Pull request closed without merging**
