### PR TITLE
feat: instrument vertx-web-openapi and vertx-web-openapi-router

### PR DESCRIPTION
**Pull request by pk-work**
add rx2 and rx3 support for vertx-web-openapi and vertx-web-openapi-router

### CODE REVIEW

**Review by tsegismont — COMMENTED** [review]
Same here, you need to add the artifact ids to the list in the maven dependency plugin config.

**Comment by pk-work** [comment]
done

**Review by tsegismont — APPROVED** [review]
LGTM, thanks

**Comment by tsegismont** [comment]
There's a build issue related to this change

**Comment by tsegismont** [comment]
There's a build issue related to this change

**Comment by tsegismont** [comment]
Thank you @pk-work !

**Pull request merged**
