### PR TITLE
Added Vert.x Oracle Client

### PR DESCRIPTION
**Pull request by tsegismont**
Oracle Client Rx bindings are not present in the stack yet

### CODE REVIEW

**Comment by tsegismont** [comment]
The build fails because, when using JDK8, the classes of the Reactive Oracle Client cannot be read.
Indeed, the module is built with JDK11:

```xml
            <configuration>
              <toolchains>
                <jdk>
                  <version>11</version>
                </jdk>
              </toolchains>
            </configuration>
```

@vietj I know the Oracle JDBC driver requires Java 11+ at runtime but have we tried to build the module with JDK8 and run tests only when JDK11+ is used?

That would help solve this stack integration issue as well as the Kotlin one: https://github.com/vert-x3/vertx-lang-kotlin/pull/215

**Comment by vietj** [comment]
you can give it a try but I think it does use a specific API of JDK 11+ related to charsets. This could be worked around with reflection maybe.

**Comment by vietj** [comment]
that is not possible because Oracle jar is compiled with bytecode of Java 11+

**Comment by vietj** [comment]
toolchain requires a specific configuration in the .m2 file, we could try to support it in this GitHub action.

**Comment by tsegismont** [comment]
Thanks for tip. I'll give it a try when we work on 4.3

**Comment by vietj** [comment]
ping @tsegismont

**Comment by tsegismont** [comment]
@vietj PTAL

The second commit message gives some details about the changes

**Review by vietj — APPROVED** [review]
LGTM, I checked the impact on the release process and it should be ok

**Pull request merged**
