### PR TITLE
Rxjava2

### PR DESCRIPTION
**Pull request by SercanKaraoglu**
I need to have ContextScheduler for RxJava2 to be able to use Schedulers, I have already done this and can commit it here

### CODE REVIEW

**Comment by vietj** [comment]
sure @SercanKaraoglu , sorry I missed your comment…

**Comment by SercanKaraoglu** [comment]
Can I have write access for committing changes @vietj

**Comment by vietj** [comment]
@SercanKaraoglu only Vert.x committers have write access to this repository (https://github.com/vert-x3/wiki/wiki/Vert.x-3-Official-stack-and-component-maintainers#vertx-committer-team)

**Comment by vietj** [comment]
did you sign-off the Eclipse CLA ?

**Comment by vietj** [comment]
and for now this should be developed in the rxjava2 branch, not in master

**Comment by SercanKaraoglu** [comment]
Yes I've signed ECA

**Comment by SercanKaraoglu** [comment]
Do I need to do something else to become vertx committer @vietj

**Comment by vietj** [comment]
ECA is necessary to become Vert.x contributor and have your contributions accepted. Becoming committer is different and requires a tail of contributions.

You should make PR from your own repository.

**Pull request closed without merging**
